// src/components/VirtualWaterFallListWasm/index.tsx
import React, {
  FC,
  useState,
  useRef,
  useEffect,
  useCallback,
  useMemo,
} from "react";
import {
  CACHE_SIZE,
  SECTION_SIZE,
  VIEW_PORT_HEIGHT,
  VIEW_PORT_WIDTH,
} from "../../constant";
import { generateDatas } from "../../utils";

import { LayerManager } from "../../pkg";

import { CellInfo, DisplayItem, ItemData } from "../../types";

import styles from "./index.module.less";

interface VirtualWaterFallList {
  height: number;
  width: number;
  collection: ItemData[];
  sectionSize: number; // 贴片越小，视窗内使用的贴片越多，收集起来的越精细，但是消耗性能。贴片越大，视窗内贴片越小，可能会有无效的元素被渲染，不过可以做缓冲区域。要结合场景使用
}

const VirtualWaterFallList: FC<VirtualWaterFallList> = ({
  height,
  width,
  collection,
  sectionSize,
}) => {
  const [displayItems, setDisplayItems] = useState<DisplayItem[]>([]);
  const [totalHeight, setTotalHeight] = useState<number>(0);
  const [totalWidth, setTotalWidth] = useState<number>(0);
  const boxRef = useRef<HTMLDivElement>(null);

  const boxStyle = useMemo(
    () => ({
      height: `${height}px`,
      width: `${width}px`,
    }),
    [width, height]
  );

  const containerStyle = useMemo(
    () => ({
      height: `${totalHeight}px`,
      width: `${totalWidth}px`,
    }),
    [totalHeight, totalWidth]
  );

  const layerManagerRef = useRef<LayerManager | null>(null);

  const collectionRef = useRef<CellInfo[]>([]);

  const flushDisplayItems = useCallback(() => {
    const boxElement = boxRef.current;
    const layerManager = layerManagerRef.current;
    const collection = collectionRef.current || [];
    if (!boxElement || !layerManager) return;
    const { scrollLeft, scrollTop } = boxElement;
    const displayItems: DisplayItem[] = [];

    const indices = layerManager.get_cell_indices({
      height: height + 2 * CACHE_SIZE,
      width: width + 2 * CACHE_SIZE,
      x: Math.max(0, scrollLeft - CACHE_SIZE),
      y: Math.max(0, scrollTop - CACHE_SIZE),
    });

    indices.forEach((indice: number) => {
      const item = collection[indice];
      displayItems.push({
        itemIndex: indice,
        key: indice,
        ...item,
      });
    });
    setDisplayItems(displayItems);
  }, [height, width]);

  const updateGridDimensions = useCallback(() => {
    const layerManager = layerManagerRef.current;
    if (!layerManager) return;
    const totalHeight = layerManager.total_height;
    const totalWidth = layerManager.total_width;
    setTotalHeight(totalHeight);
    setTotalWidth(totalWidth);
  }, []);

  const handleCollectionChange = useCallback(() => {
    const layerManager = new LayerManager(sectionSize, collection);
    layerManager.init();

    // 需要重新设置一下, 如果为null, groupManagers的引用就是[], 和ref无关, 后续会引用错误
    layerManagerRef.current = layerManager;

    updateGridDimensions();
    flushDisplayItems();
    return () => {
      layerManagerRef.current = null;
    };
  }, [sectionSize, collection]);

  useEffect(() => {
    collectionRef.current = collection;
    handleCollectionChange();
  }, [collection]);

  const getComputedStyle = useCallback((displayItem: DisplayItem) => {
    const { width, height, x, y } = displayItem;
    return {
      transform: `translateX(${x}px) translateY(${y}px) translateZ(0)`,
      width: `${width}px`,
      height: `${height}px`,
    };
  }, []);

  const resetCollection = useCallback(() => {
    handleCollectionChange();
  }, []);

  const handleContainerResize = useCallback(() => {
    resetCollection();
  }, []);

  useEffect(() => {
    if (!boxRef.current) return;
    const boxElement = boxRef.current;
    let resizeObserver: ResizeObserver;
    if (ResizeObserver) {
      resizeObserver = new ResizeObserver(handleContainerResize);
      resizeObserver.observe(boxElement);
    } else {
      boxElement.addEventListener("resize", handleContainerResize);
    }
    return () => {
      if (ResizeObserver) {
        resizeObserver.disconnect();
      } else {
        boxElement.removeEventListener("resize", handleContainerResize);
      }
    };
  }, []);

  const handleScroll = useCallback(() => {
    flushDisplayItems();
  }, []);

  return (
    <div
      className={styles["virtual-collection"]}
      ref={boxRef}
      onScroll={handleScroll}
      style={boxStyle}
    >
      <div
        className={styles["virtual-collection-container"]}
        style={containerStyle}
      >
        {displayItems.map((item: DisplayItem) => (
          <div
            className={`${styles["cell-container"]} ${styles.card} ${
              styles[item.data.color]
            }`}
            key={item.key}
            style={getComputedStyle(item)}
          >
            {item.data.text}
          </div>
        ))}
      </div>
    </div>
  );
};

export const VirtualWaterFallListInstance: FC = () => {
  const collection = generateDatas();

  return (
    <VirtualWaterFallList
      height={VIEW_PORT_HEIGHT}
      width={VIEW_PORT_WIDTH}
      sectionSize={SECTION_SIZE}
      collection={collection}
    />
  );
};

export default VirtualWaterFallList;

// vite-vue-virtual-list/src/components/WaterFallWasm/VirtualWaterFallListWasm.vue
<template>
  <div
    class="virtual-collection"
    ref="boxRef"
    @scroll="handleScroll"
    :style="boxStyle"
  >
    <div class="virtual-collection-container" :style="containerStyle">
      <div
        v-for="item in displayItems"
        :key="item.key"
        :class="`cell-container card ${item.data.color}`"
        :style="getComputedStyle(item)"
      >
        {{ item.data.text }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onUnmounted, computed } from "vue";
import { LayerManager } from "../../pkg";
import { CACHE_SIZE } from "../../constant";

interface DisplayItem {
  itemIndex: number;
  key: number;
  width: number;
  height: number;
  x: number;
  y: number;
  data: ItemData;
}

interface ItemData {
  text: string;
  color: string;
}

export default defineComponent({
  name: "VirtualWaterFallList",
  props: {
    height: {
      type: Number,
      required: true,
    },
    width: {
      type: Number,
      required: true,
    },
    collection: {
      type: Array as () => ItemData[],
      required: true,
    },
    sectionSize: {
      type: Number,
      required: true,
    },
  },
  setup(props) {
    const displayItems = ref<DisplayItem[]>([]);
    const totalHeight = ref(0);
    const totalWidth = ref(0);
    const boxRef = ref<HTMLDivElement | null>(null);
    const collectionRef = ref<ItemData[]>([]);

    const boxStyle = computed(() => ({
      height: `${props.height}px`,
      width: `${props.width}px`,
    }));

    const containerStyle = computed(() => ({
      height: `${totalHeight.value}px`,
      width: `${totalWidth.value}px`,
    }));

    const handleCollectionChange = () => {
      const layerManager = new LayerManager(
        props.sectionSize,
        props.collection
      );
      layerManager.init();

      layerManagerRef.value = layerManager;

      collectionRef.value = props.collection;

      updateGridDimensions();
      flushDisplayItems();

      return () => {
        layerManagerRef.value = null;
      };
    };

    const flushDisplayItems = () => {
      const boxElement = boxRef.value;
      const layerManager = layerManagerRef.value;
      const collection = collectionRef.value || [];
      if (!boxElement || !layerManager) return;
      const { scrollLeft, scrollTop } = boxElement;
      const displayItemsList: DisplayItem[] = [];

      const indices = layerManager.get_cell_indices({
        height: props.height + 2 * CACHE_SIZE,
        width: props.width + 2 * CACHE_SIZE,
        x: Math.max(0, scrollLeft - CACHE_SIZE),
        y: Math.max(0, scrollTop - CACHE_SIZE),
      });

      indices.forEach((index: number) => {
        const item = collection[index];
        displayItemsList.push({
          itemIndex: index,
          key: index,
          ...item,
        });
      });

      displayItems.value = displayItemsList;
    };

    const getComputedStyle = (displayItem: DisplayItem) => {
      const { width, height, x, y } = displayItem;
      return {
        transform: `translateX(${x}px) translateY(${y}px) translateZ(0)`,
        width: `${width}px`,
        height: `${height}px`,
      };
    };

    const updateGridDimensions = () => {
      const layerManager = layerManagerRef.value;
      if (!layerManager) return;
      totalHeight.value = layerManager.total_height;
      totalWidth.value = layerManager.total_width;
    };

    const handleScroll = () => {
      flushDisplayItems();
    };

    const layerManagerRef = ref<LayerManager | null>(null);

    onMounted(() => {
      collectionRef.value = props.collection;
      handleCollectionChange();
    });

    onUnmounted(() => {
      layerManagerRef.value = null;
    });

    return {
      displayItems,
      totalHeight,
      totalWidth,
      boxRef,
      boxStyle,
      containerStyle,
      handleScroll,
      getComputedStyle,
    };
  },
});
</script>

<style scoped less>
.virtual-collection {
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
}

.virtual-collection-container {
  position: relative;
}

.virtual-collection .cell-container {
  position: absolute;
  top: 0;
  left: 0;
}

.card {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: #fff;
  line-height: 100%;
  background-color: #aaa;
  border-radius: 5px;
  padding: 0;

  &.color0 {
    background-color: rgb(244, 67, 54);
  }

  &.color1 {
    background-color: rgb(255, 235, 59);
  }

  &.color2 {
    background-color: rgb(255, 152, 0);
  }

  &.color3 {
    background-color: rgb(33, 150, 243);
  }

  &.color4 {
    background-color: rgb(55, 64, 70);
  }

  &.color5 {
    background-color: rgb(103, 58, 183);
  }

  &.color6 {
    background-color: rgb(63, 81, 181);
  }

  &.color7 {
    background-color: rgb(76, 175, 80);
  }
}
</style>
